const $=s=>document.querySelector(s), host=$('#viewport');
const scene=new THREE.Scene();scene.background=new THREE.Color('#70b4c9');scene.fog=new THREE.Fog('#75b8cd',58,110);
const renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;host.prepend(renderer.domElement);
const camera=new THREE.PerspectiveCamera(45,1,.1,160);camera.position.set(0,20.3,25);camera.lookAt(0,0,-10);
scene.add(new THREE.HemisphereLight(0xc3eaff,0x737167,1.75));const sun=new THREE.DirectionalLight(0xfff0cc,3.0);sun.position.set(-18,32,10);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-18,right:18,top:35,bottom:-25,near:1,far:90});sun.shadow.bias=-.0005;sun.shadow.normalBias=.03;sun.target.position.set(0,0,-12);scene.add(sun,sun.target);
const geo={box:new THREE.BoxGeometry(1,1,1),sphere:new THREE.SphereGeometry(1,12,8),hemi:new THREE.SphereGeometry(1,16,8,0,Math.PI*2,0,Math.PI/2),cyl:new THREE.CylinderGeometry(1,1,1,12),torus:new THREE.TorusGeometry(1,.3,8,18)};
const materials={};function mat(color,rough=.65,metal=0){let key=color+':'+rough+':'+metal;return materials[key]??=new THREE.MeshStandardMaterial({color,roughness:rough,metalness:metal})}
function mesh(g,c,pos,scale,parent=scene){const m=new THREE.Mesh(geo[g],typeof c==='string'?mat(c):c);m.position.set(...pos);m.scale.set(...scale);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m}
function textTexture(text,bg='#198ddd',fg='#fff',w=256,h=128){let c=document.createElement('canvas');c.width=w;c.height=h;let a=c.getContext('2d');a.fillStyle=bg;a.fillRect(0,0,w,h);a.strokeStyle='#9eeaff';a.lineWidth=5;a.strokeRect(4,4,w-8,h-8);a.textAlign='center';a.textBaseline='middle';a.font=`900 ${h*.72}px Arial`;a.fillStyle=fg;a.fillText(text,w/2,h*.54);let tex=new THREE.CanvasTexture(c);tex.colorSpace=THREE.SRGBColorSpace;return{canvas:c,ctx:a,tex};}
function spriteLabel(text,width=2,height=1){let data=textTexture(text,'#202634');let sp=new THREE.Sprite(new THREE.SpriteMaterial({map:data.tex,depthTest:true}));sp.scale.set(width,height,1);scene.add(sp);return{sp,...data,text}}
function setLabel(a,text){if(a.text===text)return;a.text=text;let c=a.ctx;c.fillStyle='#252933';c.fillRect(0,0,256,128);c.font='900 88px Arial';c.textAlign='center';c.textBaseline='middle';c.fillStyle='white';c.fillText(text,128,70);a.tex.needsUpdate=true;}
// A lit, animated sea surrounds a full-depth bridge.
const waterGeo=new THREE.PlaneGeometry(180,200,100,100);waterGeo.rotateX(-Math.PI/2);const water=new THREE.Mesh(waterGeo,new THREE.MeshStandardMaterial({color:'#278fae',metalness:.38,roughness:.3}));water.position.set(0,-1.05,-35);scene.add(water);let waterBase=waterGeo.attributes.position.array.slice();
const ripples=new THREE.InstancedMesh(geo.box,new THREE.MeshBasicMaterial({color:'#acdce5',transparent:true,opacity:.26}),450);ripples.frustumCulled=false;scene.add(ripples);const rippleSeeds=Array.from({length:450},(_,i)=>({x:(i%2?1:-1)*(6.2+(Math.sin(i*87.6)*.5+.5)*33),z:-65+(Math.cos(i*31.2)*.5+.5)*95,w:.12+(Math.sin(i*3)*.5+.5)*.9}));
mesh('box','#687985',[0,-.48,-24],[12,.8,110]);mesh('box','#a6a9a9',[0,-.035,-24],[11.4,.14,110]);
const roadMarks=[];for(let i=0;i<28;i++){let m=mesh('box','#e1dcd2',[-.2,.048,-60+i*3.2],[.065,.009,1.8]);m.castShadow=false;roadMarks.push(m)}
const seams=[];for(let i=0;i<22;i++){let m=mesh('box','#a09f9c',[0,.047,-60+i*4.5],[11.3,.006,.025]);m.castShadow=false;seams.push(m)}
const posts=[];for(let side of[-1,1]){mesh('box','#d0ccc2',[side*5.7,.13,-24],[.26,.4,110]);mesh('box','#697780',[side*5.8,.52,-24],[.13,.12,110]);mesh('box','#85919a',[side*5.8,.92,-24],[.14,.12,110]);for(let i=0;i<27;i++){let group=new THREE.Group();scene.add(group);mesh('box','#8a959c',[0,.55,0],[.4,1.3,.5],group);mesh('box','#d8d5c9',[0,1.22,0],[.52,.12,.62],group);group.position.set(side*5.8,0,-65+i*3.5);posts.push(group)}}
const panelTex=textTexture('+1');const panelMat=new THREE.MeshStandardMaterial({map:panelTex.tex,roughness:.32,metalness:.1});const panelFaceGeo=new THREE.PlaneGeometry(.99,.78);const panels=[];for(let i=0;i<64;i++){let g=new THREE.Group();scene.add(g);mesh('box','#1384d3',[0,.48,0],[1.05,.96,.18],g);mesh('box','#61c9ff',[0,1.01,-.03],[1.12,.12,.25],g);let face=new THREE.Mesh(panelFaceGeo,panelMat);face.position.set(0,.53,.099);g.add(face);g.scale.x=.42;g.position.set(5.44,0,10-i*1.05);panels.push(g)}
// Draw repeated bridge components together to keep large battles smooth.
const environmentRoots=scene.children.slice(),environmentGroups=new Map();scene.updateMatrixWorld(true);
for(let root of environmentRoots)root.traverse(obj=>{if(obj.isMesh&&(obj.geometry===geo.box||obj.geometry===panelFaceGeo)){let key=obj.geometry.uuid+obj.material.uuid+obj.castShadow;if(!environmentGroups.has(key))environmentGroups.set(key,[]);environmentGroups.get(key).push(obj);}});
const environmentBatches=[];for(let list of environmentGroups.values()){let first=list[0],m=new THREE.InstancedMesh(first.geometry,first.material,list.length);m.castShadow=first.castShadow;m.receiveShadow=true;m.frustumCulled=false;list.forEach((o,i)=>{m.setMatrixAt(i,o.matrixWorld);o.visible=false});scene.add(m);environmentBatches.push({m,list});}
function updateEnvironment(){for(let r of environmentRoots)r.updateMatrixWorld(true);for(let b of environmentBatches){b.list.forEach((o,i)=>b.m.setMatrixAt(i,o.matrixWorld));b.m.instanceMatrix.needsUpdate=true;}}
// Shared articulated rig; each body part is instanced across the entire squad.
const dummy=new THREE.Object3D(), poseRoot=new THREE.Group(), bones={root:poseRoot};
function bone(name,parent,x,y,z){let b=new THREE.Group();b.position.set(x,y,z);bones[parent].add(b);bones[name]=b;return b}
bone('torso','root',0,.83,0);bone('head','torso',0,.64,0);bone('gun','torso',.24,.12,.35);
for(let side of[-1,1]){let s=side<0?'L':'R';bone('thigh'+s,'root',side*.17,.66,0);bone('shin'+s,'thigh'+s,0,-.29,0);bone('foot'+s,'shin'+s,0,-.25,.035);bone('arm'+s,'torso',side*.30,.31,0);bone('hand'+s,'arm'+s,0,-.22,.015)}
function characterParts(team){let blue=team==='blue',coat=blue?'#1475c8':'#b62e30',armor=blue?'#194d74':'#6c3537',helmet=blue?'#238fd7':'#d44335';let parts=[];
 const p=(b,g,c,pos,scale,rot=[0,0,0],metal=0,rough=.55)=>parts.push({bone:b,g,c,pos,scale,rot,metal,rough});
 p('torso','sphere',coat,[0,.1,0],[.31,.35,.225]);
 p('torso','box',armor,[0,.11,.18],[.5,.43,.12]);p('torso','box','#263f4d',[0,-.14,.02],[.54,.11,.38]);p('torso','box','#e7b567',[0,-.14,.228],[.105,.08,.035],undefined,.5);
 for(let side of[-1,1]){p('torso','box','#bdac79',[side*.16,.12,.263],[.105,.26,.065]);p('torso','box',armor,[side*.18,-.08,.26],[.13,.15,.095]);p('torso','sphere',coat,[side*.30,.29,0],[.14,.16,.22]);p('torso','box','#b4c9c9',[side*.42,.3,.005],[.03,.065,.18]);}
 p('torso','box',blue?'#285b69':'#61463d',[0,.1,-.245],[.44,.44,.22]);p('torso','box','#829178',[0,.26,-.38],[.34,.06,.055]);p('torso','box','#143b47',[0,.025,-.38],[.34,.035,.045]);
 p('torso','cyl','#8a9d88',[0,.37,-.25],[.11,.45,.11],[0,0,Math.PI/2]);p('torso','box','#273f47',[-.17,.12,-.385],[.045,.5,.025]);p('torso','box','#273f47',[.17,.12,-.385],[.045,.5,.025]);
 p('torso','cyl','#273f47',[-.2,.49,-.27],[.013,.4,.013],[0,0,-.14]);
 if(blue){for(let j=0;j<6;j++)p('torso','cyl','#d4aa58',[-.17+j*.065,.22-j*.035,-.4],[.025,.12,.025],[0,0,-.48],.6);p('torso','box','#c5e6ee',[0,.1,-.406],[.11,.05,.018]);}
 p('head','sphere','#edbd8a',[0,-.03,.015],[.255,.265,.235]);p('head','sphere','#dca270',[0,-.09,.235],[.07,.06,.07]);
 p('head','hemi',helmet,[0,.065,0],[.335,.32,.335],undefined,.18,.3);p('head','cyl',helmet,[0,.065,0],[.342,.055,.34],undefined,.15,.32);
 p('head','box','#284151',[0,.005,.239],[.44,.125,.085]);for(let side of[-1,1]){p('head','box',blue?'#83ddf0':'#ffd387',[side*.11,.01,.29],[.16,.07,.014],undefined,.5,.18);p('head','sphere',armor,[side*.27,-.03,0],[.07,.11,.11]);}
 p('head','box',blue?'#d1e8e5':'#ead5a4',[0,.388,-.015],[.09,.022,.22]);p('head','box','#33414b',[0,-.25,.08],[.15,.04,.08]);
 for(let side of[-1,1]){let s=side<0?'L':'R';p('thigh'+s,'sphere',armor,[0,-.135,0],[.135,.205,.14]);p('shin'+s,'sphere','#354653',[0,-.12,0],[.115,.175,.12]);p('shin'+s,'sphere','#677579',[0,-.025,.098],[.112,.105,.055]);p('foot'+s,'sphere','#23323b',[0,.018,.07],[.145,.12,.225]);p('foot'+s,'box','#1b2930',[0,-.058,.06],[.27,.05,.36]);
 p('arm'+s,'sphere',coat,[0,-.12,0],[.13,.19,.145]);p('hand'+s,'sphere','#d4a478',[0,-.085,0],[.105,.15,.105]);p('hand'+s,'sphere','#243d47',[0,-.2,.015],[.11,.115,.12]);}
 p('gun','box','#293c46',[0,0,.13],[.14,.16,.48],undefined,.6,.3);p('gun','box','#768082',[0,.045,.34],[.16,.085,.28],undefined,.65,.3);p('gun','cyl','#24343c',[0,.025,.64],[.045,.38,.045],[Math.PI/2,0,0],.6,.25);p('gun','box','#81663e',[0,-.145,.08],[.11,.21,.14],[.15,0,0]);p('gun','box','#344b53',[0,.13,.1],[.075,.08,.16]);
 return parts;
}
function pose(a,blue,time){let phase=time*(blue?11+(a.phase??0)%3*.18:10)+(a.phase??0),sin=Math.sin(phase),cos=Math.cos(phase);let dying=a.death!==undefined,age=dying?a.death:0;let lean=blue?THREE.MathUtils.clamp(battle.velocity*.018,-.2,.2):Math.sin(phase*.5)*.025;
 poseRoot.position.set(a.x,.032+Math.abs(sin)*.045,a.z);poseRoot.rotation.set(0,blue?Math.PI:0,-lean);poseRoot.scale.setScalar(dying?Math.max(.01,1-Math.max(0,age-.55)*1.8):1+((a.variant??2)-3)*.012);
 if(dying){poseRoot.rotation.x=-Math.min(1,age/.32)*1.55;poseRoot.position.y=.13;poseRoot.position.z-=Math.min(age,.35)*1.9;}
 bones.torso.rotation.set(-.07+cos*.025,Math.sin(phase)*.055,Math.sin(phase)*.035);bones.head.rotation.set(.035,Math.sin(phase*.5)*.035,-Math.sin(phase)*.025);
 let recoil=blue?Math.max(0,1-((battle.time+(a.phase??0)*.013)%(.24-battle.level*.018))/.09):0;bones.gun.position.z=.35-recoil*.085;bones.gun.rotation.x=-recoil*.1;
 if(!blue&&battle.time-(a.hitAt??-10)<.13)bones.torso.rotation.x=-.35;
 for(let side of[-1,1]){let s=side<0?'L':'R',v=sin*side;bones['thigh'+s].rotation.x=v*.48;bones['shin'+s].rotation.x=.12+Math.max(0,-v)*.82;bones['foot'+s].rotation.x=-.12-Math.max(0,v)*.15;
 bones['arm'+s].rotation.set(-.86+cos*.035+recoil*.07,0,side*.1);bones['hand'+s].rotation.set(-.63,0,-side*.22);}
 poseRoot.updateMatrixWorld(true);
}
function batch(team,max){let groups=new Map();for(let s of characterParts(team)){let material=mat(s.c,s.rough,s.metal),key=s.g+material.uuid;dummy.position.set(...s.pos);dummy.rotation.set(...s.rot);dummy.scale.set(...s.scale);dummy.updateMatrix();if(!groups.has(key))groups.set(key,{geometry:geo[s.g],material,parts:[]});groups.get(key).parts.push({s,local:dummy.matrix.clone()});}return Array.from(groups.values()).map(g=>{let m=new THREE.InstancedMesh(g.geometry,g.material,max*g.parts.length);m.instanceMatrix.setUsage(THREE.DynamicDrawUsage);m.castShadow=true;m.receiveShadow=true;m.frustumCulled=false;m.count=0;scene.add(m);return{m,parts:g.parts}})}
const allies=batch('blue',64),foes=batch('red',750),composeMatrix=new THREE.Matrix4();
function renderBatch(batch,actors,blue,time){for(let p of batch)p.m.count=actors.length*p.parts.length;for(let i=0;i<actors.length;i++){pose(actors[i],blue,time);for(let p of batch)for(let j=0;j<p.parts.length;j++){let part=p.parts[j];composeMatrix.multiplyMatrices(bones[part.s.bone].matrixWorld,part.local);p.m.setMatrixAt(i*p.parts.length+j,composeMatrix)}}for(let p of batch)p.m.instanceMatrix.needsUpdate=true;}
// Bind-pose parts for the separately animated commander.
function specs(team){poseRoot.position.set(0,0,0);poseRoot.rotation.set(0,0,0);poseRoot.scale.setScalar(1);for(let[name,b]of Object.entries(bones))b.rotation.set(0,0,0);poseRoot.updateMatrixWorld(true);return characterParts(team).map(s=>{dummy.position.set(...s.pos);dummy.rotation.set(...s.rot);dummy.scale.set(...s.scale);dummy.updateMatrix();composeMatrix.multiplyMatrices(bones[s.bone].matrixWorld,dummy.matrix);let v=new THREE.Vector3(),q=new THREE.Quaternion(),sc=new THREE.Vector3();composeMatrix.decompose(v,q,sc);return[s.g,s.c,v.toArray(),sc.toArray(),q]});}

const bossGroup=new THREE.Group();scene.add(bossGroup);for(let s of specs('red')){let part=mesh(s[0],s[1],s[2],s[3],bossGroup);part.quaternion.copy(s[4]);}bossGroup.scale.setScalar(3.5);for(let i=0;i<5;i++)mesh('box','#e8ad37',[0,1.77,.18-i*.09],[.1,.22,.065],bossGroup);mesh('sphere','#731e26',[0,.98,-.18],[.39,.38,.22],bossGroup);for(let side of[-1,1])for(let i=0;i<3;i++){let sp=mesh('cyl','#d9d5c4',[side*(.28+i*.06),1.2,-.02],[.035,.19,.035],bossGroup);sp.rotation.z=side*-.55;}
mesh('sphere','#bb3633',[0,.97,0],[.44,.41,.29],bossGroup);mesh('sphere','#e6b07b',[0,.77,.19],[.32,.28,.19],bossGroup);for(let side of[-1,1]){mesh('sphere','#cd4037',[side*.41,1.1,0],[.22,.23,.23],bossGroup);mesh('sphere','#e5b581',[side*.44,.86,.1],[.16,.27,.16],bossGroup);mesh('sphere','#6d342d',[side*.44,.63,.13],[.19,.16,.18],bossGroup);}mesh('box','#493936',[0,.6,.1],[.63,.12,.4],bossGroup);mesh('box','#e7b953',[0,.61,.32],[.14,.13,.05],bossGroup);
const bulletMat=new THREE.MeshBasicMaterial({color:'#fff1a0'}),bulletMesh=new THREE.InstancedMesh(geo.sphere,bulletMat,2200);bulletMesh.frustumCulled=false;scene.add(bulletMesh);
const flashMat=new THREE.MeshBasicMaterial({color:'#ffffc3'}),flashes=new THREE.InstancedMesh(geo.sphere,flashMat,64);scene.add(flashes);flashes.frustumCulled=false;
const fxMesh=new THREE.InstancedMesh(geo.box,new THREE.MeshBasicMaterial({color:'#fff2bd'}),900);fxMesh.frustumCulled=false;scene.add(fxMesh);let fx=[];
const blockViews=new Map();function blockView(b){let g=new THREE.Group();scene.add(g);for(let i=-1;i<=1;i++){let tire=mesh('torus','#30343a',[i*.64,.78,0],[.58,.58,.63],g);for(let j=0;j<12;j++){let angle=j/12*Math.PI*2;let tread=mesh('box','#454a50',[i*.64+Math.cos(angle)*.62,.78+Math.sin(angle)*.62,0],[.18,.13,.46],g);tread.rotation.z=angle}}
let pedestal=mesh('box','#e7bc5b',[0,1.56,0],[1.2,.1,.65],g);mesh('box','#2f91d1',[0,1.82,0],[.65,.3,.38],g);mesh('box','#254652',[0,1.9,.44],[.12,.12,.65],g);let label=spriteLabel(String(b.hp),1.7,.8);return{g,label}}
const ring=mesh('torus',new THREE.MeshBasicMaterial({color:'#68cfff',transparent:true,opacity:.22}),[0,.08,5],[1.7,1.7,.09]);ring.rotation.x=Math.PI/2;
const battle=new Battle();let clock=0,accum=0,previous=0,paused=false,muted=true,audioCtx=null,toastUntil=0,shake=0,zoomKick=0,lastMode='ready',corpses=[],shockwaves=[],casings=[],recruitPulse=0;const reducedMotion=matchMedia('(prefers-reduced-motion: reduce)').matches;
function sound(type){if(muted)return;try{audioCtx??=new AudioContext();let o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type==='fire'?'triangle':'sine';o.frequency.setValueAtTime(type==='fire'?100:type==='damage'?80:700,audioCtx.currentTime);o.frequency.exponentialRampToValueAtTime(type==='fire'?40:220,audioCtx.currentTime+.07);g.gain.setValueAtTime(type==='fire'?.012:.035,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+.08);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+.09)}catch{}}
function toast(text){$('#toast').textContent=text;toastUntil=clock+2.7}
const contacts=new THREE.InstancedMesh(new THREE.CircleGeometry(.35,16),new THREE.MeshBasicMaterial({color:'#18303a',transparent:true,opacity:.18,depthWrite:false}),800);scene.add(contacts);contacts.frustumCulled=false;
const casingMesh=new THREE.InstancedMesh(geo.cyl,mat('#e5b64d',.27,.65),450);scene.add(casingMesh);casingMesh.frustumCulled=false;
const warningMat=new THREE.MeshBasicMaterial({color:'#ff6549',transparent:true,opacity:.3,depthWrite:false});const warningStrip=mesh('box',warningMat,[0,.08,-5],[2.8,.012,25]);warningStrip.castShadow=false;warningStrip.visible=false;
const hazardMesh=new THREE.InstancedMesh(geo.torus,new THREE.MeshBasicMaterial({color:'#ffbb6b',transparent:true,opacity:.75}),12);scene.add(hazardMesh);hazardMesh.frustumCulled=false;
let floating=[],dustTimer=0;
function shock(x,z,color,size=3){let m=new THREE.Mesh(geo.torus,new THREE.MeshBasicMaterial({color,transparent:true,opacity:.8,depthWrite:false}));m.rotation.x=-Math.PI/2;m.position.set(x,.12,z);scene.add(m);shockwaves.push({mesh:m,age:0,size});}
function floatingText(x,z,text){let f=spriteLabel(text,.95,.47);f.sp.position.set(x,2.5,z);f.sp.material.depthTest=false;f.age=0;floating.push(f);}
function burst(e,amount,color='#ffcc75',dust=false){for(let j=0;j<amount;j++)fx.push({x:e.x,y:dust?.1:.9,z:e.z,vx:(Math.random()-.5)*(dust?1:5),vy:Math.random()*(dust?.4:5),vz:(Math.random()-.5)*5,life:.35+Math.random()*.4,color,dust});if(fx.length>900)fx.splice(0,fx.length-900)}
function processEvents(){for(let e of battle.events){
 if(e.type==='hit'){burst(e,5);corpses.push({x:e.x,z:e.z,phase:e.value,death:0});}
 if(e.type==='spark')burst(e,3,'#ffe9a3');
 if(e.type==='recruit'){sound('recruit');recruitPulse=.25;floatingText(4.8,4,'+1');shock(4.9,4,'#64edff',.9);$('#troops').classList.remove('pop');void $('#troops').offsetWidth;$('#troops').classList.add('pop');}
 if(e.type==='fire'){sound('fire');for(let i=0;i<battle.n;i+=3){let a=battle.formation(i);casings.push({x:a.x-.36,y:1.1,z:a.z-.25,vx:-1-Math.random(),vy:1+Math.random()*2,vz:Math.random()-.5,age:0,rot:Math.random()*6});}if(casings.length>450)casings.splice(0,casings.length-450);}
 if(e.type==='damage'){if(!reducedMotion)shake=.12;burst(e,13,'#eaa680');sound('damage');$('#damageFlash').style.opacity=.55;}
 if(e.type==='upgrade'){burst(e,65,'#ffd36b');shock(e.x,e.z,'#ffd36b',4);toast('화력 강화 · LEVEL '+e.value);if(!reducedMotion){zoomKick=1.4;shake=.075}sound('upgrade');}
 if(e.type==='boss')toast('거대 지휘관 등장');
 if(e.type==='warning')toast('충격파 예고 · 붉은 구역에서 벗어나세요');
 if(e.type==='slam'){if(!reducedMotion)shake=.22;shock(e.x,e.z,'#ffb165',5);burst(e,35,'#d5bda0',true);sound('damage');}
 if(e.type==='won'){burst(e,200,'#ffe7aa');shock(e.x,e.z,'#fff1b4',9);toast('다리 확보 완료');}
 }battle.events=[];}
function renderEffects(dt,actors,moving){
 let all=[...actors,...battle.enemies.slice(0,650)];contacts.count=all.length;all.forEach((a,i)=>{dummy.position.set(a.x,.052,a.z);dummy.rotation.set(-Math.PI/2,0,0);dummy.scale.set(1,.8,1);dummy.updateMatrix();contacts.setMatrixAt(i,dummy.matrix)});contacts.instanceMatrix.needsUpdate=true;
 if(moving){dustTimer-=dt;if(dustTimer<=0){dustTimer=.16;actors.filter((a,i)=>i%5===0).forEach(a=>burst({x:a.x,z:a.z+.12},1,'#c3bcac',true));}}
 if(!paused)casings.forEach(p=>{p.age+=dt;p.x+=p.vx*dt;p.z+=p.vz*dt;p.y+=p.vy*dt;p.vy-=dt*10;if(p.y<.065){p.y=.065;p.vy=Math.abs(p.vy)*.23;p.vx*=.7}});casings=casings.filter(p=>p.age<1.4);casingMesh.count=casings.length;casings.forEach((p,i)=>{dummy.position.set(p.x,p.y,p.z);dummy.rotation.set(p.rot+p.age*12,p.age*6,Math.PI/2);dummy.scale.set(.022,.08,.022);dummy.updateMatrix();casingMesh.setMatrixAt(i,dummy.matrix)});casingMesh.instanceMatrix.needsUpdate=true;
 for(let w of shockwaves){if(!paused)w.age+=dt;let progress=w.age/.65,scale=.1+progress*w.size;w.mesh.scale.set(scale,scale,.035);w.mesh.material.opacity=Math.max(0,(1-progress)*.7)}shockwaves=shockwaves.filter(w=>{if(w.age>.65){scene.remove(w.mesh);w.mesh.material.dispose();return false}return true});
 for(let f of floating){if(!paused){f.age+=dt;f.sp.position.y+=dt*1.6}f.sp.material.opacity=Math.max(0,1-f.age/1.1)}floating=floating.filter(f=>{if(f.age>1.1){scene.remove(f.sp);f.tex.dispose();f.sp.material.dispose();return false}return true});
 warningStrip.visible=battle.boss.active&&battle.boss.attack<1&&battle.mode==='playing';warningStrip.position.set(battle.boss.aim,.08,(battle.boss.z+5)/2);warningStrip.scale.z=5-battle.boss.z;warningMat.opacity=.13+Math.sin(battle.time*22)*.1;
 hazardMesh.count=Math.min(12,battle.hazards.length);battle.hazards.slice(0,12).forEach((h,i)=>{dummy.position.set(h.x,.18,h.z);dummy.rotation.set(-Math.PI/2,0,0);dummy.scale.set(1.5,.36,.16);dummy.updateMatrix();hazardMesh.setMatrixAt(i,dummy.matrix)});hazardMesh.instanceMatrix.needsUpdate=true;
 recruitPulse=Math.max(0,recruitPulse-dt);panels.forEach(m=>m.children[0].material.emissive.setHex(recruitPulse>0?0x063959:0));
 $('#damageFlash').style.opacity=Math.max(0,(+$('#damageFlash').style.opacity||0)-dt*2);
}

function render(dt){let moving=battle.mode==='playing'&&!paused,animation=battle.mode==='ready'?clock*.35:battle.time;let offset=(battle.mode==='ready'?clock*.22:battle.time)*1.4;
roadMarks.forEach((m,i)=>m.position.z=-65+(i*3.2+offset)%89.6);seams.forEach((m,i)=>m.position.z=-65+(i*4.5+offset)%99);posts.forEach((m,i)=>m.position.z=-65+((i%27)*3.5+offset)%94.5);panels.forEach((m,i)=>m.position.z=10-((i*1.05-offset)%67.2+67.2)%67.2);
let verts=waterGeo.attributes.position.array;for(let i=0;i<verts.length;i+=3)verts[i+1]=Math.sin(waterBase[i]*1.1+clock*.9)*.055+Math.cos(waterBase[i+2]*.7+clock)*.08;waterGeo.attributes.position.needsUpdate=true;
rippleSeeds.forEach((p,i)=>{dummy.position.set(p.x+Math.sin(clock*.3+i)*.15,-.87,p.z+Math.sin(clock*.4+i)*.2);dummy.rotation.set(0,0,0);dummy.scale.set(p.w*(.8+Math.sin(clock+i)*.2),.008,.018);dummy.updateMatrix();ripples.setMatrixAt(i,dummy.matrix)});ripples.instanceMatrix.needsUpdate=true;
let actors=Array.from({length:battle.n},(_,i)=>battle.formation(i));renderBatch(allies,actors,true,animation);if(moving)corpses.forEach(a=>a.death+=dt);corpses=corpses.filter(a=>a.death<1.1);renderBatch(foes,[...battle.enemies.slice(0,650),...corpses.slice(-90)],false,animation);
bossGroup.position.set(battle.boss.x,Math.abs(Math.sin(animation*3))*.07,battle.boss.z);let windup=battle.boss.active&&battle.boss.attack<1;bossGroup.rotation.z=Math.sin(animation*2)*.045;bossGroup.rotation.x=windup?-.22*Math.sin((1-battle.boss.attack)*Math.PI/2):Math.sin(animation*4)*.035;bossGroup.scale.y=3.5*(1+Math.sin(animation*3)*.018);bossGroup.visible=battle.mode!=='won';
for(let b of battle.blocks){let v=blockViews.get(b.id);if(!v){v=blockView(b);blockViews.set(b.id,v)}v.g.position.set(b.x,0,b.z);v.g.rotation.z=Math.sin(clock*70)*Math.max(0,.1-(battle.time-b.hitAt))*.7;v.label.sp.position.set(b.x,1.2,b.z+.55);setLabel(v.label,String(Math.ceil(b.hp)))}for(let[id,v]of blockViews)if(!battle.blocks.some(b=>b.id===id)){scene.remove(v.g,v.label.sp);v.label.tex.dispose();v.label.sp.material.dispose();blockViews.delete(id)}
bulletMat.color.set(battle.level>=3?'#68eeff':'#ffed75');bulletMesh.count=Math.min(2200,battle.shots.length);for(let i=0;i<bulletMesh.count;i++){let s=battle.shots[i];dummy.position.set(s.x,1.02,s.z);dummy.rotation.set(0,0,0);dummy.scale.set(.048,.048,.41);dummy.updateMatrix();bulletMesh.setMatrixAt(i,dummy.matrix)}bulletMesh.instanceMatrix.needsUpdate=true;
flashes.count=moving?actors.length:0;for(let i=0;i<flashes.count;i++){let a=actors[i],pulse=Math.max(0,1-((battle.time+a.phase*.013)%(.24-battle.level*.018))/.055);dummy.position.set(a.x-.24,1.02,a.z-.96);dummy.rotation.set(0,0,clock*30+i);dummy.scale.set(.17*pulse,.12*pulse,.29*pulse);dummy.updateMatrix();flashes.setMatrixAt(i,dummy.matrix)}flashes.instanceMatrix.needsUpdate=true;
if(!paused)fx.forEach(p=>{p.life-=dt;p.x+=p.vx*dt;p.z+=p.vz*dt;p.y+=p.vy*dt;p.vy-=dt*(p.dust?.3:12)});fx=fx.filter(p=>p.life>0);fxMesh.count=fx.length;fx.forEach((p,i)=>{dummy.position.set(p.x,Math.max(.06,p.y),p.z);dummy.rotation.set(p.life*5,p.life*8,0);dummy.scale.setScalar(p.life*(p.dust?.21:.14));dummy.updateMatrix();fxMesh.setMatrixAt(i,dummy.matrix);fxMesh.setColorAt(i,new THREE.Color(p.color||'#ffcf7d'))});fxMesh.instanceMatrix.needsUpdate=true;if(fxMesh.instanceColor)fxMesh.instanceColor.needsUpdate=true;renderEffects(dt,actors,moving);
ring.position.set(battle.x,.09,PLAYER_Z+(Math.ceil(battle.n/Math.ceil(Math.sqrt(Math.max(1,battle.n))))-1)*.35);ring.scale.set(Math.min(battle.halfWidth()+.55,5.5-Math.abs(battle.x)),.8+Math.ceil(battle.n/Math.ceil(Math.sqrt(Math.max(1,battle.n))))*.32,.012);
camera.position.x=battle.x*.025+Math.sin(clock*47)*shake;camera.position.y=20.3+Math.cos(clock*53)*shake*.55;camera.fov=45-zoomKick;camera.updateProjectionMatrix();shake*=Math.exp(-dt*13);zoomKick*=Math.exp(-dt*5);updateEnvironment();renderer.render(scene,camera);
$('#troops').textContent=battle.n;$('#kills').textContent=battle.kills;$('#level').textContent='LV. '+battle.level;$('#fill').style.width=Math.min(100,battle.time/50*100)+'%';$('#phase').textContent=battle.boss.active?'BOSS FIGHT':'BRIDGE 01';$('#bossHud').hidden=!battle.boss.active||battle.mode==='won';$('#bossFill').style.width=Math.max(0,battle.boss.hp/battle.boss.max*100)+'%';$('#toast').style.opacity=clock<toastUntil?1:0;
if(battle.mode!==lastMode){if(battle.mode==='won'||battle.mode==='lost'){ $('#menu').hidden=false;$('#menuTitle').textContent=battle.mode==='won'?'다리 확보 완료':'다시, 전진하라';$('#menuDesc').textContent=`${battle.kills}명 처치 · 병력 ${battle.n} · 화력 LV. ${battle.level}`;$('#start').textContent='다시 도전';}lastMode=battle.mode}
$('#viewport').dataset.state=JSON.stringify({mode:battle.mode,paused,time:Math.round(battle.time),troops:battle.n,kills:battle.kills,level:battle.level,bossHP:Math.round(battle.boss.hp),enemies:battle.enemies.length,x:+battle.x.toFixed(3),left:+(battle.x-battle.halfWidth()).toFixed(3),right:+(battle.x+battle.halfWidth()).toFixed(3),version:'2.0',fps:displayFPS,drawCalls:renderer.info.render.calls});
}
const keys={};let dragging=false;
function setPointer(e){if(battle.mode!=='playing'||paused)return;let r=renderer.domElement.getBoundingClientRect();let left=new THREE.Vector3(-ROAD_LIMIT,.8,4.5).project(camera),right=new THREE.Vector3(ROAD_LIMIT,.8,4.5).project(camera);let lo=r.left+(left.x+1)*.5*r.width,hi=r.left+(right.x+1)*.5*r.width;let ratio=THREE.MathUtils.clamp((e.clientX-lo)/(hi-lo),0,1);battle.setTarget((ratio*2-1)*ROAD_LIMIT);}
renderer.domElement.addEventListener('pointerdown',e=>{dragging=true;renderer.domElement.setPointerCapture(e.pointerId);setPointer(e)});renderer.domElement.addEventListener('pointermove',e=>{if(dragging)setPointer(e)});renderer.domElement.addEventListener('pointerup',()=>dragging=false);renderer.domElement.addEventListener('pointercancel',()=>dragging=false);
function pause(){if(battle.mode!=='playing')return;paused=!paused;$('#pause').textContent=paused?'▶':'Ⅱ';$('#pauseScreen').hidden=!paused;$('#pause').setAttribute('aria-label',paused?'계속하기':'일시정지')}
window.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault();keys[e.key]=true;if(e.key===' '&&!e.repeat)pause()});window.addEventListener('keyup',e=>keys[e.key]=false);document.addEventListener('visibilitychange',()=>{if(document.hidden&&battle.mode==='playing'&&!paused)pause()});window.addEventListener('blur',()=>{Object.keys(keys).forEach(k=>delete keys[k]);dragging=false;if(battle.mode==='playing'&&!paused)pause()});
$('#start').onclick=()=>{for(let v of blockViews.values()){scene.remove(v.g,v.label.sp);v.label.tex.dispose();v.label.sp.material.dispose()}blockViews.clear();battle.reset();paused=false;accum=0;fx=[];corpses=[];casings=[];shockwaves.forEach(w=>scene.remove(w.mesh));shockwaves=[];zoomKick=0;floating.forEach(f=>{scene.remove(f.sp);f.tex.dispose();f.sp.material.dispose()});floating=[];$('#pauseScreen').hidden=true;$('#pause').textContent='Ⅱ';$('#pause').setAttribute('aria-label','일시정지');$('#menu').hidden=true;toast('오른쪽 +1 패널에서 병력을 모으세요')};$('#pause').onclick=pause;$('#resume').onclick=pause;$('#retry').onclick=()=>$('#start').click();$('#sound').onclick=()=>{muted=!muted;$('#sound').textContent=muted?'소리 OFF':'소리 ON';if(!muted)sound('upgrade')};
function resize(){let r=host.getBoundingClientRect();renderer.setSize(r.width,r.height);camera.aspect=r.width/r.height;camera.updateProjectionMatrix()}window.addEventListener('resize',resize);resize();
let fpsWindow=0,fpsFrames=0,displayFPS=0;function tick(ms){fpsWindow+=(ms-previous)/1000;fpsFrames++;if(fpsWindow>=1){displayFPS=Math.round(fpsFrames/fpsWindow);fpsWindow=0;fpsFrames=0}let dt=Math.min(.05,(ms-previous)/1000||.016);previous=ms;clock+=dt;if(battle.mode==='playing'&&!paused){let direction=(keys.ArrowRight||keys.d?1:0)-(keys.ArrowLeft||keys.a?1:0);battle.setTarget(battle.target+direction*dt*7);accum+=dt;while(accum>=1/60){battle.update(1/60);accum-=1/60}processEvents()}render(dt);requestAnimationFrame(tick)}requestAnimationFrame(tick);
