const mapGroups=new Map(),propGeometries={},mapWeatherPositions=new Float32Array(350*3);
function propGeometry(name,snow=false){let key=name+(snow?'snow':'');if(propGeometries[key])return propGeometries[key];let data=PROP_DATA[name],g=new THREE.BufferGeometry(),colors=data.color.slice();if(snow)for(let i=0;i<data.leaf.length;i++)if(data.leaf[i]){colors[i*3]=.89;colors[i*3+1]=.96;colors[i*3+2]=1}g.setAttribute('position',new THREE.Float32BufferAttribute(data.position,3));g.setAttribute('normal',new THREE.Float32BufferAttribute(data.normal,3));g.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));return propGeometries[key]=g;}
const propMaterial=new THREE.MeshStandardMaterial({vertexColors:true,roughness:.85});
function importedProp(name,parent,x,z,size,snow=false){let geometry=propGeometry(name,snow);geometry.computeBoundingBox();let bounds=geometry.boundingBox,span=Math.max(bounds.max.x-bounds.min.x,bounds.max.z-bounds.min.z),scale=name==='rock'?size/span:size;let safeX=Math.sign(x)*Math.max(Math.abs(x),6.3+span*scale*.6);let m=new THREE.Mesh(geometry,propMaterial);m.position.set(safeX,-.05,z);m.scale.setScalar(scale);m.rotation.y=(x+z)*1.31;m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
function mapObject(parent,geometry,color,p,s){return mesh(geometry,color,p,s,parent)}
function buildMap(index){let group=new THREE.Group();scene.add(group);group.visible=false;let theme=STAGES[index].theme;
 for(let side of[-1,1])for(let i=0;i<13;i++){let z=12-i*6.8,x=side*(7.2+(i%3)*1.1),r=.8+((i*13)%7)*.12;
  if(theme==='ocean'){if(i%3===0){mapObject(group,'sphere','#b6bc8a',[side*12,-1.1,z],[4.6,1.3,5.2]);importedProp('palm',group,side*12,z,6.5);importedProp('rock',group,side*9.8,z+2,1.7)}}
  if(theme==='desert'){importedProp('cactus',group,x,z,2.6*r);if(i%2===0){let rock=importedProp('rock',group,side*10.1,z-2,4*r);rock.material=mat('#ab684b',.95);mapObject(group,'sphere','#d6a167',[side*17,-.9,z],[7,2.2,8]);}}
  if(theme==='snow'){importedProp('pine',group,x,z,5.5*r,true);let rock=importedProp('rock',group,side*6.9,z+2,1.3*r);rock.material=mat('#d7e6ed',.8);if(i%3===0)mapObject(group,'sphere','#eaf4f7',[side*12,-.9,z],[5,3.2,6])}
  if(theme==='city'){let height=4+(i*7%6);mapObject(group,'box',i%2?'#657682':'#465864',[x+side*.8,height/2-.1,z],[2.4,height,3.4]);mapObject(group,'box','#34454f',[x+side*.8,height+.1,z],[2.6,.25,3.6]);for(let floor=0;floor<height-1;floor+=1.2)for(let col of[-.8,0,.8])mapObject(group,'box',floor%2?'#829caa':'#eac991',[x+side*.8+col,1+floor,z+1.72],[.39,.5,.035]);if(i%3===0){mapObject(group,'cyl','#3d4b55',[side*6.2,1.8,z+2],[.05,3.6,.05]);mapObject(group,'box','#efd598',[side*6.2,3.7,z+2],[.45,.15,.55])}}
  if(theme==='lava'){let rock=importedProp('rock',group,x,z,3*r);rock.material=mat('#39313e',.85);let spire=mapObject(group,'cyl','#413545',[side*10,2.5*r,z],[.8,5*r,.8]);spire.rotation.z=side*.16;mapObject(group,'box',new THREE.MeshBasicMaterial({color:'#ff9940'}),[side*6.3,-.045,z],[.6,.02,3.2]);}
 }
 if(theme==='desert'){mapObject(group,'box','#a95f43',[-6.3,3.8,-43],[1.1,7.6,1.4]);mapObject(group,'box','#a95f43',[6.3,3.8,-43],[1.1,7.6,1.4]);mapObject(group,'box','#bd7850',[0,7.5,-43],[13.7,1.1,1.6]);}
 if(theme==='lava'){let cone=new THREE.Mesh(new THREE.ConeGeometry(8,11,7),mat('#4e3441'));cone.position.set(13,4.5,-44);group.add(cone);mapObject(group,'torus',new THREE.MeshBasicMaterial({color:'#ff9f3f'}),[13,9.7,-44],[1.4,1.4,.4]).rotation.x=Math.PI/2;}
 // Repeated scenery is combined into a small number of draw calls.
 group.updateMatrixWorld(true);let buckets=new Map();group.traverse(o=>{if(o.isMesh){let key=o.geometry.uuid+o.material.uuid;if(!buckets.has(key))buckets.set(key,[]);buckets.get(key).push(o)}});let merged=new THREE.Group();scene.add(merged);for(let list of buckets.values()){let m=new THREE.InstancedMesh(list[0].geometry,list[0].material,list.length);m.castShadow=true;m.receiveShadow=true;m.frustumCulled=false;list.forEach((o,i)=>m.setMatrixAt(i,o.matrixWorld));merged.add(m)}scene.remove(group);mapGroups.set(index,merged);return merged;
}
const weatherGeo=new THREE.BufferGeometry();for(let i=0;i<350;i++){mapWeatherPositions[i*3]=Math.sin(i*17.3)*13;mapWeatherPositions[i*3+1]=(i*.47)%13;mapWeatherPositions[i*3+2]=-48+(i*.73)%61}weatherGeo.setAttribute('position',new THREE.BufferAttribute(mapWeatherPositions,3));
const weatherMaterial=new THREE.PointsMaterial({color:'#ffffff',size:.06,transparent:true,opacity:.7,depthWrite:false});const weather=new THREE.Points(weatherGeo,weatherMaterial);scene.add(weather);let currentTheme=-1;
function applyStageTheme(index){if(index===currentTheme)return;currentTheme=index;let config=STAGES[index];for(let g of mapGroups.values())g.visible=false;(mapGroups.get(index)||buildMap(index)).visible=true;
 scene.background.set(config.sky);scene.fog.color.set(config.sky);water.material.color.set(config.ground);water.material.roughness=config.theme==='ocean'?.3:.8;water.material.metalness=config.theme==='ocean'?.38:0;water.material.emissive.set(config.theme==='lava'?'#b7350e':'#000000');water.material.emissiveIntensity=config.theme==='lava'?.65:0;water.position.y=['ocean','lava'].includes(config.theme)?-1.05:-.18;
 mat('#a6a9a9').color.set(config.road);mat('#d0ccc2').color.set(config.theme==='snow'?'#eaf4ff':config.theme==='lava'?'#74636e':config.theme==='desert'?'#dbb78b':'#bcc3c6');mat('#8a959c').color.set(config.theme==='lava'?'#5d4c5b':config.theme==='desert'?'#b38d6b':'#82919a');
 ripples.visible=config.theme==='ocean'||config.theme==='lava';ripples.material.color.set(config.theme==='lava'?'#ffd976':'#acdce5');sun.color.set(config.theme==='lava'?'#ffb490':config.theme==='snow'?'#d7edff':'#fff0cc');renderer.toneMappingExposure=config.theme==='lava'?1.3:1.1;
 weather.visible=config.theme!=='ocean';weatherMaterial.color.set(config.theme==='snow'?'#ffffff':config.theme==='lava'?'#ffb458':config.theme==='desert'?'#f7cf93':'#b9cad4');weatherMaterial.size=config.theme==='snow'?.075:.045;
 document.documentElement.style.setProperty('--accent',config.accent);$('#operationLabel').textContent=config.subtitle;$('#mapCaption').textContent=config.name;document.querySelectorAll('[data-stage]').forEach(b=>b.setAttribute('aria-pressed',+b.dataset.stage===index?'true':'false'));
}
function renderMapWeather(dt){let theme=battle.config.theme;if(weather.visible){for(let i=0;i<350;i++){let j=i*3;mapWeatherPositions[j+1]+=dt*(theme==='lava'?1.7:-1.5);if(mapWeatherPositions[j+1]<0)mapWeatherPositions[j+1]=13;if(mapWeatherPositions[j+1]>13)mapWeatherPositions[j+1]=0;mapWeatherPositions[j]+=(theme==='snow'?.3:.65)*dt;if(mapWeatherPositions[j]>14)mapWeatherPositions[j]=-14}weatherGeo.attributes.position.needsUpdate=true;}}
